services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: flask-backend
    volumes:
      - ../backend/media:/app/media
      - ../backend/static:/app/static
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ../.env

  nginx:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ../backend/media:/app/media:ro
      - ../backend/static:/app/static:ro
    restart: unless-stopped
    env_file:
      - ../.env

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: