services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: flask-backend
    volumes:
      - ../backend/media:/app/media
      - ../backend/static:/app/static
      - ./sqlite:/app/instance
    ports:
      - "5000:5000"
    env_file:
      - ../.env

  nginx:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"                   # добавляем HTTPS порт
    depends_on:
      - backend
    volumes:
      - ../frontend/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/dist:/usr/share/nginx/html
      - ../backend/media:/app/media:ro
      - ../backend/static:/app/static:ro
      - ./certbot/conf:/etc/letsencrypt       # монтируем папку с сертификатами
      - ./certbot/www:/var/www/certbot         # монтируем папку для challenge файлов
    restart: unless-stopped
    env_file:
      - ../.env