services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: flask-backend
    volumes:
      - ../backend/media:/app/media
      - ../backend/static:/app/static
    ports:
      - "5000:5000"
    env_file:
      - ../.env

  nginx:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ../backend/media:/app/media:ro
      - ../backend/static:/app/static:ro
    restart: unless-stopped
    env_file:
      - ../.env
