services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: flask-backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ../backend/media:/app/media
      - ../backend/static:/app/static
      - ./sqlite:/app/instance
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    restart: unless-stopped

  nginx:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: nginx-proxy
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ../media:/app/media:ro
      - ../backend/static:/app/static:ro
      - ../frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    env_file:
      - ../.env


volumes:
  pgdata: